tasks:
  - init: npm install
    command: npm run start
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - github.vscode-pull-request-github
    - github.vscode-codeql
    - eamodio.gitlens
    - coenraads.bracket-pair-colorizer-2
    - dbaeumer.vscode-eslint
