tasks:
  - init: npm install
    command: npm run start
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - github.vscode-pull-request-github
    - github.vscode-codeql
    - eamodio.gitlens
    - dbaeumer.vscode-eslint
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - coenraads.bracket-pair-colorizer
